export const ItemList = [
    { title: "New", txt: "新商品列表", url: "#" },
    { title: "New", txt: "3月8日發售商品", url: "#" },
    { title: "New", txt: "2月28日發售商品", url: "#" },
    { title: "New", txt: "2月26日發售商品", url: "#" },
    { title: "New", txt: "2月21日發售商品", url: "#" },
    { title: "New", txt: "2月14日發售商品", url: "#" },
    { title: "New", txt: "2月7日發售商品", url: "#" },
    { title: "New", txt: "1月31日發售商品", url: "#" },
    { title: "New", txt: "1月24日發售商品", url: "#" },
    { title: "New", txt: "1月17日發售商品", url: "#" },
    { title: "Restocked", txt: "補貨產品列表", url: "#" },
    { title: "Restocked", txt: "3月6日重新上貨商品", url: "#" },
    { title: "Restocked", txt: "2月27日重新上貨商品", url: "#" },
    { title: "Restocked", txt: "2月20日重新上貨商品", url: "#" },
    { title: "Character", txt: "吉伊卡哇", url: "#" },
    { title: "Character", txt: "烏薩奇", url: "#" },
    { title: "Character", txt: "小八", url: "#" },
    { title: "Character", txt: "小桃", url: "#" },
    { title: "Character", txt: "栗子饅頭", url: "#" },
    { title: "Character", txt: "海獺勇者", url: "#" },
    { title: "Character", txt: "古本屋", url: "#" },
    { title: "Character", txt: "那孩子", url: "#" },
    { title: "Character", txt: "大強", url: "#" },
    { title: "Character", txt: "奧德", url: "#" },
    { title: "Character", txt: "奇美拉", url: "#" },
    { title: "Character", txt: "盔甲人", url: "#" },
    { title: "Character", txt: "小甲蟲", url: "#" },
    { title: "Character", txt: "哥布林", url: "#" },
    { title: "Character", txt: "星星", url: "#" },
    { title: "Series", txt: "吉伊卡哇 平行世界!?", url: "#" },
    { title: "Series", txt: "吉伊卡哇蛋糕", url: "#" },
    { title: "Series", txt: "吉伊卡哇壽司", url: "#" },
    { title: "Series", txt: "吉伊卡哇 獅薩爺慶典!!!&獅薩的特產店", url: "#" },
    { title: "Series", txt: "吉伊卡哇X讀賣巨人", url: "#" },
    { title: "Series", txt: "吉伊卡哇拉麵豬", url: "#" },
    { title: "Series", txt: "真的假的吉伊卡哇&超級真的假的吉伊卡哇", url: "#" },
    { title: "Series", txt: "吉伊卡哇餐廳", url: "#" },
    { title: "Series", txt: "吉伊卡哇x版急電車", url: "#" },
    { title: "Series", txt: "吉伊卡哇/霍克斯", url: "#" },
    { title: "Series", txt: "吉伊卡哇出門去玩!", url: "#" },
    { title: "Series", txt: "吉伊卡哇水族館", url: "#" },
    { title: "Series", txt: "吉伊卡哇 天使與惡魔", url: "#" },
    { title: "Series", txt: "吉伊卡哇x三麗歐", url: "#" },
    { title: "Series", txt: "吉伊卡哇 東京特產", url: "#" },
    { title: "Series", txt: "吉伊卡哇 哇哇幼兒園", url: "#" },
    { title: "Series", txt: "吉伊卡哇飯店", url: "#" },
    { title: "Series", txt: "吉伊卡哇蘭度", url: "#" },
    { title: "Category", txt: "玩偶與吊飾", url: "#" },
    { title: "Category", txt: "雜貨", url: "#" },
    { title: "Category", txt: "室內用品", url: "#" },
    { title: "Category", txt: "服飾", url: "#" },
    { title: "Category", txt: "靜止的", url: "#" },
    { title: "Category", txt: "毛巾", url: "#" },
    { title: "Category", txt: "廚房", url: "#" },
    { title: "Category", txt: "PC/智能手機商品", url: "#" },
    { title: "Category", txt: "便利", url: "#" },
    { title: "Category", txt: "戶外", url: "#" },
    { title: "Category", txt: "玩具/拼圖", url: "#" },
    { title: "Category", txt: "食物", url: "#" },
    { title: "Category", txt: "保留產品", url: "#" },
    { title: "Category", txt: "所有商品", url: "#" }
];