export const CategoryData = [
    { txt: "玩偶與吊飾" },
    { txt: "雜貨" },
    { txt: "室內用品" },
    { txt: "服飾" },
    { txt: "靜止的" },
    { txt: "毛巾" },
    { txt: "廚房" },
    { txt: "PC/智能手機商品" },
    { txt: "便利" },
    { txt: "戶外" },
    { txt: "玩具/拼圖" },
    { txt: "食物" },
    { txt: "保留產品" },
    { txt: "所有商品" },
];